# coding: utf-8

"""
    Speech Services API version 3.2

    Speech Services API version 3.2.  # noqa: E501

    OpenAPI spec version: 3.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.file_properties import FileProperties  # noqa: E501
from swagger_client.rest import ApiException


class TestFileProperties(unittest.TestCase):
    """FileProperties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFileProperties(self):
        """Test FileProperties"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.file_properties.FileProperties()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
