# coding: utf-8

"""
    Speech Services API version 3.2

    Speech Services API version 3.2.  # noqa: E501

    OpenAPI spec version: 3.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.custom_speech_operations_api import CustomSpeechOperationsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCustomSpeechOperationsApi(unittest.TestCase):
    """CustomSpeechOperationsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.custom_speech_operations_api.CustomSpeechOperationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_operations_get_model_copy(self):
        """Test case for operations_get_model_copy

        Gets the operation identified by the given ID.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
