# coding: utf-8

"""
    Speech Services API version 3.2

    Speech Services API version 3.2.  # noqa: E501

    OpenAPI spec version: 3.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.web_hook_events import WebHookEvents  # noqa: E501
from swagger_client.rest import ApiException


class TestWebHookEvents(unittest.TestCase):
    """WebHookEvents unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWebHookEvents(self):
        """Test WebHookEvents"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.web_hook_events.WebHookEvents()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
