# coding: utf-8

"""
    Speech Services API version 3.2

    Speech Services API version 3.2.  # noqa: E501

    OpenAPI spec version: 3.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.model_manifest import ModelManifest  # noqa: E501
from swagger_client.rest import ApiException


class TestModelManifest(unittest.TestCase):
    """ModelManifest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelManifest(self):
        """Test ModelManifest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.model_manifest.ModelManifest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
